name: Web → S3 + CloudFront

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Determine upload dir
        id: dir
        run: |
          if [ -d "web/dist" ]; then echo "path=web/dist" >> $GITHUB_OUTPUT
          else echo "path=web" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 sync "${{ steps.dir.outputs.path }}/" "s3://${{ secrets.S3_BUCKET }}/" --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${{ secrets.CF_DISTRIBUTION_ID }}" \
            --paths "/*"
