name: Web → S3 + CloudFront

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: web-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Access Key 사용 시 permissions는 사실 불필요(OIDC 전환 시 유지)
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Determine upload dir
        id: dir
        run: |
          if [ -d "web/dist" ]; then echo "path=web/dist" >> $GITHUB_OUTPUT
          elif [ -d "web" ]; then echo "path=web" >> $GITHUB_OUTPUT
          else echo "path=." >> $GITHUB_OUTPUT; fi

      - name: Who am I? (STS)
        run: aws sts get-caller-identity

      - name: Upload to S3 (dry-run)
        run: |
          aws s3 sync "${{ steps.dir.outputs.path }}/" "s3://${{ secrets.S3_BUCKET }}/" \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --dryrun

      - name: Upload to S3 (apply)
        run: |
          aws s3 sync "${{ steps.dir.outputs.path }}/" "s3://${{ secrets.S3_BUCKET }}/" \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*"

      # (선택) 캐시 헤더 설정 — 필요할 때 주석 해제
      # - name: Cache headers (HTML short, assets long)
      #   run: |
      #     aws s3 cp "${{ steps.dir.outputs.path }}/" "s3://${{ secrets.S3_BUCKET }}/" \
      #       --recursive --exclude "*" --include "*.html" \
      #       --cache-control "no-cache, no-store, must-revalidate" \
      #       --metadata-directive REPLACE
      #     for ext in css js png jpg jpeg gif svg webp ico woff woff2 ttf eot map; do
      #       aws s3 cp "${{ steps.dir.outputs.path }}/" "s3://${{ secrets.S3_BUCKET }}/" \
      #         --recursive --exclude "*" --include "*.$ext" \
      #         --cache-control "max-age=31536000, immutable" \
      #         --metadata-directive REPLACE || true
      #     done

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${{ secrets.DISTRIBUTION_ID }}" \
            --paths "/*"
